SoccerShirts/Controllers/CamisaController.cs
using Microsoft.AspNetCore.Mvc;
using SoccerShirts.Models;
using SoccerShirts.Repositories;
using SoccerShirts.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SoccerShirts.Controllers
{
    public class CamisaController : Controller
    {
        private readonly ICamisaRepository _camisaRepository;
        private ICategoriaRepository _categoriaRepository;

        public CamisaController(ICamisaRepository camisaRepository, ICategoriaRepository categoriaRepository)
        {
            _camisaRepository = camisaRepository;
            _categoriaRepository = categoriaRepository;
        }

        public IActionResult ListarCamisas(string categoria)
        {
            string _categoria = categoria;
            IEnumerable<Camisa> camisas;
            string categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(categoria) || string.Equals("Todas as camisas", _categoria, StringComparison.OrdinalIgnoreCase))
            {
                camisas = _camisaRepository.Camisa.OrderBy(c => c.CamisaId);
                categoria = "Todas as camisas";
            }
            else
            {
                if (string.Equals("Nacional", _categoria, StringComparison.OrdinalIgnoreCase))
                {
                    camisas = _camisaRepository.Camisa.Where(c => c.Categoria.CategoriaNome.Equals("Nacional")).OrderBy(c => c.Nome);
                }

                else if (string.Equals("Internacional", _categoria, StringComparison.OrdinalIgnoreCase))
                {
                    camisas = _camisaRepository.Camisa.Where(c => c.Categoria.CategoriaNome.Equals("Internacional")).OrderBy(c => c.Nome);
                }

                else
                {
                    camisas = _camisaRepository.Camisa.Where(c => c.Categoria.CategoriaNome.Equals("Seleção")).OrderBy(c => c.Nome);
                }

                categoriaAtual = _categoria;
            }

            var camisasListViewModel = new CamisaListViewModel
            {
                Camisas = camisas,
                CategoriaAtual = categoriaAtual

            };
            return View (camisasListViewModel);
        }

        public IActionResult Details (int camisaId)
        {
            var camisa = _camisaRepository.Camisa.FirstOrDefault(c => c.CamisaId == camisaId);
            if (camisa == null)
            {
                return View("~/Views/Error/Error.cshtml");
            }
            else
            {
                return View(camisa);
            }
        }


        public IActionResult Search (string searchString)
        {
            string _searchString = searchString;
            IEnumerable<Camisa> camisas;
            string _categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(_searchString))
            {
                camisas = _camisaRepository.Camisa.OrderBy(c => c.CamisaId);
            }
            else
            {
                camisas = _camisaRepository.Camisa.Where(c => c.Nome.ToLower().Contains(_searchString));
            }

            return View("~/Views/Camisa/ListarCamisas.cshtml", new CamisaListViewModel { Camisas = camisas, CategoriaAtual = "Todas as camisas" });

        }
    }
}

SoccerShirts/Controllers/CarrinhoDeCompraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SoccerShirts.Models;
using SoccerShirts.Repositories;
using SoccerShirts.ViewModels;

namespace SoccerShirts.Controllers
{
    [Authorize]
    public class CarrinhoDeCompraController : Controller
    {
        private readonly ICamisaRepository _camisaRepositoy;
        private CarrinhoCompra _carrinhoCompra;

        public CarrinhoDeCompraController(ICamisaRepository camisaRepository,
            CarrinhoCompra carrinhoCompra)
        {
            _camisaRepositoy = camisaRepository;
            _carrinhoCompra = carrinhoCompra;
        }

        [Authorize]
        // Exibe o carrinho de Compra
        public IActionResult Index()
        {
            var itens = _carrinhoCompra.GetCarrinhoCompraItens();
            _carrinhoCompra.CarrinhoDeCompraItems = itens;

            var carrinhoCompraViewModel = new CarrinhoCompraViewModel
            {
            CarrinhoCompra = _carrinhoCompra,
            CarrinhoCompraTotal = _carrinhoCompra.GetValorCarrinhoCompraTotal()
            };
            return View(carrinhoCompraViewModel);
        }
        // Adiciona um item ao Carrinho e após retorna a página Index
        
        [Authorize]
        public RedirectToActionResult AdicionarItemNoCarrinhoCompra (int camisaId)
        {
            var camisaSelecionada = _camisaRepositoy.Camisa.FirstOrDefault(c => c.CamisaId == camisaId);

            if (camisaSelecionada != null)
            {
                _carrinhoCompra.AdicionarCarrinho(camisaSelecionada, 1);
            }

            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult RemoverItemDoCarrinhoCompra(int camisaId)
        {
            var camisaSelecionada = _camisaRepositoy.Camisa.FirstOrDefault(c => c.CamisaId == camisaId);

            if (camisaSelecionada != null)
            {
                _carrinhoCompra.RemoverDoCarrinho(camisaSelecionada);
            }

            return RedirectToAction("Index");
        }
    }
}

SoccerShirts/Controllers/ContatoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SoccerShirts.Controllers
{
    public class ContatoController : Controller
    {
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }
    }
}

SoccerShirts/Views/Shared/_CamisaResumo.cshtml
@model Camisa

<div class="col-md-4 col-sm-4 col-lg-4">
    <img src="@Model.ImagemUrl" class="card-img-top imageResponsive" alt="@Model.Nome" />
    <div class="figure-caption">
        <h4 class="formPullRightButton">@Model.Preco.ToString("c")</h4>
        <h4>
            <a asp-controller="Camisa" asp-action="Details" asp-route-CamisaId="@Model.CamisaId">@Model.Nome</a>
        </h4>
        <h6>@Model.DescricaoCurta</h6>
    </div>
    <div text-right">
        <p class="formPullRightButton">
            <a class="btn btn-primary" asp-controller="CarrinhoDeCompra" asp-action="AdicionarItemNoCarrinhoCompra" asp-route-CamisaId="@Model.CamisaId">
                Incluir no Carrinho
            </a>
        </p>
    </div>
</div>

SoccerShirts/Views/Shared/_Carousel.cshtml
<div id="carouselCamisas" class="carousel slide marginTop1" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselCamisas" data-slide-to="0" class="active"></li>
        <li data-target="#carouselCamisas" data-slide-to="1"></li>
        <li data-target="#carouselCamisas" data-slide-to="2"></li>
        <li data-target="#carouselCamisas" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/imagens/BannerMG.jpg" class="d-block w-100" alt="Camisa">
        </div>
        <div class="carousel-item">
            <img src="~/imagens/BannerAmericaSul.jpg" class="d-block w-100" alt="Camisa">
        </div>
        <div class="carousel-item">
            <img src="~/imagens/BannerRJ.jpg" class="d-block w-100" alt="Camisa">
        </div>
        <div class="carousel-item">
            <img src="~/imagens/BannerEuropa.jpg" class="d-block w-100" alt="Camisa">
        </div margin="10px">
    </div>
    <a class="left carousel-control" href="#carouselCamisas" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carouselCamisas" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>

SoccerShirts/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SoccerShirts</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SoccerShirts</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @if (User.Identity.IsAuthenticated)
                    {
                        @await Component.InvokeAsync("CarrinhoCompraResumo");
                    }
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    @await Component.InvokeAsync("CategoriaMenu")
                    <a class="nav-link text-light" asp-area="" asp-controller="Contato" asp-action="Index">Contato</a>

                    @if (User.IsInRole("Admin"))
                    {
                        <a class="nav-link text-light" asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a>
                    }

                    <form class="navbar-form navbar-right" asp-controller="Lanche" asp-action="Search" method="get">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Procurar uma camisa" name="searchString" value="@ViewData["searchString"]">
                        </div>
                    </form>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SoccerShirts
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>